In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

In [2]:
# dcahce 데이터 가져오기
dl = open('doutput.txt','r')
data = dl.read().splitlines()

In [3]:
# 파일 명으로 데이터 구분하기
title = title = [s for s in data if 'File: ' in s]
title_index = [i for i in range(len(data)) if 'File: ' in data[i]]

In [6]:
# 결과가 존재하는 파일의 index만 추출
success_data_index = []
for i in range(len(title_index)-1):
    gap = title_index[i] - title_index[i+1]
    if gap == -74:
        j = title_index[i]
        success_data_index.append(j)

# 위의 코드로는 제일 마지막 파일이 포함되지 않아서 추가적으로 확인
if (title_index[-1] - len(data)) == -74:
    success_data_index.append(title_index[-1])

In [16]:
# 앞서 찾은 인덱스 목록으로 데이터 가져오기
sim_title = []
sim_data = []
for i in success_data_index:
    sim_title.append(data[i][11:(len(data[i])-4)].split('_'))
    sim_data.append(data[i+3:i+71])

In [22]:
# 제목의 정보와 통계값의 정보를 각각의 데이터 프레임으로 만듦 (데이터 추출을 편하게 하기 위함)_icache
cache_title_df = pd.DataFrame(columns = ['dl1','dl1_nsets','dl1_bsize','dl1_assoc','dl1_repl','dl2','dl2_nsets','dl2_bsize','dl2_assoc','dl2_repl'],data = sim_title)
cache_simul_df = pd.DataFrame(columns = ['sim_num_insn','sim_num_refs','sim_elapsed_time','sim_inst_rate','il1.accesses','il1.hits',
  'il1.misses','il1.replacements','il1.writebacks','il1.invalidations','il1.miss_rate','il1.repl_rate',
  'il1.wb_rate','il1.inv_rate','dl1.accesses','dl1.hits','dl1.misses','dl1.replacements','dl1.writebacks',
  'dl1.invalidations','dl1.miss_rate','dl1.repl_rate','dl1.wb_rate','dl1.inv_rate','dl2.accesses','dl2.hits',
  'dl2.misses','dl2.replacements','dl2.writebacks','dl2.invalidations','dl2.miss_rate','dl2.repl_rate','dl2.wb_rate',
  'dl2.inv_rate','itlb.accesses','itlb.hits','itlb.misses','itlb.replacements','itlb.writebacks','itlb.invalidations',
  'itlb.miss_rate','itlb.repl_rate','itlb.wb_rate','itlb.inv_rate','dtlb.accesses','dtlb.hits','dtlb.misses',
  'dtlb.replacements','dtlb.writebacks','dtlb.invalidations','dtlb.miss_rate','dtlb.repl_rate','dtlb.wb_rate',
  'dtlb.inv_rate','ld_text_base','ld_text_size','ld_data_base','ld_data_size','ld_stack_base','ld_stack_size',
  'ld_prog_entry','ld_environ_base','ld_target_big_endian','mem.page_count','mem.page_mem','mem.ptab_misses','mem.ptab_accesses','mem.ptab_miss_rate'], data = sim_data)

In [23]:
## cache_simul_df에 있는 문자들을 제거하고 필요한 데이터만 저장함
Data = []
for i in range(len(cache_simul_df)):
    row = []
    for j in cache_simul_df.columns.tolist():
        row.append(cache_simul_df.iloc[i].loc[j][len(j):cache_simul_df.iloc[i].loc[j].find("#")-1])
    Data.append(row)

cache_data_df = pd.DataFrame(columns = cache_simul_df.columns.tolist(), data = Data)

In [24]:
# title 데이터 프레임과 data 데이터 프레임을 합쳐서 하나의 데이터 프레임으로 만듦
cache_df = pd.concat([cache_title_df,cache_data_df],axis = 1)

In [25]:
# 시뮬레이션에 성공은 했지만 오류가 발생한 데이터 제거
refine = []
for i in range(len(cache_df)):
    if int(cache_df['sim_num_insn'][i])!=0 :
        refine.append(i)
useful_data = cache_df.iloc[refine]

In [3]:
# 데이터 백업 및 타입 변경을 위한 csv파일 저장 및 읽기
#useful_data.to_csv('dcache_simul_useful_data.csv',index = False)
Data_df = pd.read_csv('dcache_simul_useful_data.csv')

In [4]:
Data_df.head()

,dl1,dl1_nsets,dl1_bsize,dl1_assoc,dl1_repl,dl2,dl2_nsets,dl2_bsize,dl2_assoc,dl2_repl,...,ld_stack_base,ld_stack_size,ld_prog_entry,ld_environ_base,ld_target_big_endian,mem.page_count,mem.page_mem,mem.ptab_misses,mem.ptab_accesses,mem.ptab_miss_rate
0,dl1,4,256,4,l,dl2,1,4096,8,r,...,0x011ff9b000,16384,0x012002e530,0x011ff97000,0,301,2408k,2431,7155370,0.0003
1,dl1,8,256,2,r,dl2,64,64,8,f,...,0x011ff9b000,16384,0x012002e530,0x011ff97000,0,267,2136k,268,4347304,0.0001
2,dl1,2,256,8,r,dl2,16,512,4,r,...,0x011ff9b000,16384,0x012002e530,0x011ff97000,0,301,2408k,2431,7155370,0.0003
3,dl1,128,8,4,f,dl2,2,2048,8,f,...,0x011ff9b000,16384,0x012002e530,0x011ff97000,0,301,2408k,2431,7155370,0.0003
4,dl1,4,128,8,f,dl2,128,32,4,r,...,0x011ff9b000,16384,0x012002e530,0x011ff97000,0,267,2136k,268,4347304,0.0001

In [5]:
# 분석을 진행할 항목만 추출
target_df = Data_df.iloc[:,[1,2,3,4,6,7,8,9,26,30,36,40]]

In [6]:
# 분석의 가정을 활용하기 위해 il2_size 계산해서 추가하기
dl2_size = pd.DataFrame(columns = ['dl2_size'],data = np.array(target_df.iloc[:,4])*np.array(target_df.iloc[:,5])*np.array(target_df.iloc[:,6]))
target_df1 = pd.concat([dl2_size,target_df],axis = 1)

In [7]:
target_df1

,dl2_size,dl1_nsets,dl1_bsize,dl1_assoc,dl1_repl,dl2_nsets,dl2_bsize,dl2_assoc,dl2_repl,dl1.misses,dl1.miss_rate,dl2.misses,dl2.miss_rate
0,32768,4,256,4,l,1,4096,8,r,18075,0.0447,16494,0.2533
1,32768,8,256,2,r,64,64,8,f,1,1.0000,1,1.0000
2,32768,2,256,8,r,16,512,4,r,16385,0.0406,6408,0.1007
3,32768,128,8,4,f,2,2048,8,f,26888,0.0665,7993,0.0892
4,16384,4,128,8,f,128,32,4,r,1,1.0000,1,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27715,32768,32,32,4,f,512,64,1,l,11173,0.0277,17135,0.2869
27716,8192,2,512,4,f,8,1024,1,f,32374,0.0801,44242,0.5217
27717,8192,512,8,1,f,1,512,16,l,31004,0.0767,13785,0.1446
27718,16384,4,512,2,f,8,256,8,l,1,1.0000,1,1.0000
27719,16384,1,512,8,r,64,64,4,f,1,1.0000,1,1.0000

In [ ]:
sns.pairplot(target_df1)

In [ ]:
# il2_size 별로 데이터 분리
ratio2 = []
ratio4 = []
ratio8 = []
for i in range(len(target_df1)):
    division = target_df1.iloc[i,0]
    if division == 8192:
        ratio2.append(i)
    elif division == 16384:
        ratio4.append(i)
    else:
        ratio8.append(i)

ratio2_df = target_df1.iloc[ratio2]
ratio4_df = target_df1.iloc[ratio4]
ratio8_df = target_df1.iloc[ratio8]

In [ ]:
#ratio2에서 가장 missrate가 낮은 구성을 il1기준, il2 기준으로 각각 가져옴
ratio2_df.sort_values('dl1.miss_rate').head(6)

In [ ]:
ratio2_df.sort_values('dl2.miss_rate').head(6)

In [ ]:
# 위에서 진행한 결과는 각각의 구성이 매우 달라 종합적인 판단을 위해 AMAT 계산 
# (l1 hit time = 1, l1 miss penalty = 10, l2 miss penalty 100)로 가정한다.
amat = 1 + ratio2_df.iloc[:,-3]*10 + ratio2_df.iloc[:,-3]*ratio2_df.iloc[:,-1]*100
amat_df = pd.DataFrame(columns = ['amat'], data = amat)
ratio2_amat_df = pd.concat([ratio2_df, amat_df],axis = 1)

In [ ]:
ratio2_amat_df.sort_values('amat').head(9)

In [ ]:
#회귀분석을 통해 각 항목이 어느정도의 영향력이 있는지 확인함
x_data = ratio2_amat_df.iloc[:,[1,2,3,5,6,7]].values
ydata = ratio2_amat_df.iloc[:,-1].values
xdata = sm.add_constant(x_data, has_constant = 'add')

multi_model = sm.OLS(ydata, xdata)
fitted_multi_model = multi_model.fit()
fitted_multi_model.summary()

In [ ]:
sns.pairplot(ratio2_amat_df)

In [ ]:
# ratio4의 경우도 계산함
amat = 1 + ratio4_df.iloc[:,-3]*10 + ratio4_df.iloc[:,-3]*ratio4_df.iloc[:,-1]*100
amat_df = pd.DataFrame(columns = ['amat'], data = amat)
ratio4_amat_df = pd.concat([ratio4_df, amat_df],axis = 1)
ratio4_amat_df.sort_values('amat').head(9)

In [ ]:
#회귀분석을 통해 각 항목이 어느정도의 영향력이 있는지 확인함
x_data = ratio4_amat_df.iloc[:,[1,2,3,5,6,7]].values
ydata = ratio4_amat_df.iloc[:,-1].values
xdata = sm.add_constant(x_data, has_constant = 'add')

multi_model = sm.OLS(ydata, xdata)
fitted_multi_model = multi_model.fit()
fitted_multi_model.summary()

In [ ]:
sns.pairplot(ratio4_amat_df, vars = ['dl1_nsets','dl1_bsize','dl1_assoc','dl2_nsets','dl2_bsize','dl2_assoc','amat'])

In [ ]:
# ratio8의 경우도 계산함
amat = 1 + ratio8_df.iloc[:,-3]*10 + ratio8_df.iloc[:,-3]*ratio8_df.iloc[:,-1]*100
amat_df = pd.DataFrame(columns = ['amat'], data = amat)
ratio8_amat_df = pd.concat([ratio8_df, amat_df],axis = 1)
ratio8_amat_df.sort_values('amat').head(9)

In [ ]:
#회귀분석을 통해 각 항목이 어느정도의 영향력이 있는지 확인함
x_data = ratio8_amat_df.iloc[:,[1,2,3,5,6,7]].values
ydata = ratio8_amat_df.iloc[:,-1].values
xdata = sm.add_constant(x_data, has_constant = 'add')

multi_model = sm.OLS(ydata, xdata)
fitted_multi_model = multi_model.fit()
fitted_multi_model.summary()

In [ ]:
sns.pairplot(ratio8_amat_df, vars = ['dl1_nsets','dl1_bsize','dl1_assoc','dl2_nsets','dl2_bsize','dl2_assoc','amat'])